# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 05:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20160304_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255)),
                ('transaction_date', models.DateTimeField()),
                ('domain', models.CharField(max_length=15)),
                ('latitude', models.CharField(max_length=15)),
                ('card_type', models.CharField(max_length=32)),
                ('bank', models.CharField(max_length=255)),
                ('card_digits', models.CharField(max_length=4)),
                ('authorization_code', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Billing',
                'verbose_name_plural': 'Billings',
            },
        ),
        migrations.DeleteModel(
            name='LocationModel',
        ),
    ]
