# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 05:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160313_0502'),
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='workspace.Organisation'),
        ),
        migrations.AlterUniqueTogether(
            name='billing',
            unique_together=set([('reference', 'authorization_code')]),
        ),
    ]
