"""
Django settings for panda project.

Generated by 'django-admin startproject' using Django 1.8.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'r04=z95t^(mcw_9ahqtjkb=h(qflaadvow=kuh#-vl8g$qt4e+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('ENV', False)

ALLOWED_HOSTS = ["*"]

HOST = 'apipanda.com'


# Application definition

INSTALLED_APPS = (
    'jet.dashboard',
    'jet',
    'django.contrib.admin',
    'django.contrib.humanize',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles'
)


THIRD_PARTY_APPS = (
    'experiments',
    'tastypie',
    'jsonfield',
    'jsonfield2',
    'django_ace',
    'kong_admin',
    'django_extensions'
)

LOCAL_APPS = (
    'app',
    'workspace',
    'endpoint',
    'plugin'
)

INSTALLED_APPS += THIRD_PARTY_APPS + LOCAL_APPS


MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'experiments.middleware.ExperimentsRetentionMiddleware',
)

ROOT_URLCONF = 'panda.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'public/app/views')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ]
        },
    },
]

WSGI_APPLICATION = 'panda.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

if not DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'NAME': os.getenv('DB_NAME', 'panda'),
            'PORT': os.getenv('DB_PORT', 5432),
            'USER': os.getenv('DB_USER', 'bernard'),
            'PASSWORD': os.getenv('DB_PASS', '[]')
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }


# Authntication Backends
AUTHENTICATION_BACKENDS = (
    "app.backends.AuthBackend",
)

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/assets/'
STATIC_ROOT = os.path.join(BASE_DIR, "public")


STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "public/site"),
    os.path.join(BASE_DIR, "public/app")
)

TASTYPIE_ALLOW_MISSING_SLASH = True
TASTYPIE_DEFAULT_FORMATS = ['json', 'jsonp']

TASTYPIE_API_VERSION = 'v1'

KONG_ADMIN_URL = 'http://localhost:8001'
KONG_ADMIN_SIMULATOR = False

JET_DEFAULT_THEME = 'light-gray'
